### PR TITLE
Drop pinecard version

### PR DESCRIPTION
**Pull request by felixhekhorn**
related to https://github.com/NNPDF/runcards/pull/159

since the original behaviour resulted into a failure I suggest to drop the pinecard for the moment completely and then do the proper job in https://github.com/NNPDF/pinefarm/issues/15

### CODE REVIEW

**Comment by AleCandido** [comment]
> since the original behaviour resulted into a failure I suggest to drop the pinecard for the moment completely and then do the proper job in #15

I would do the other way round...

**Comment by cschwan** [comment]
How would you do it?

**Comment by AleCandido** [comment]
Provide directly the alternative, before dropping the current behavior.

**Comment by cschwan** [comment]
In other words: fix #15 first, then this issue. I agree with that.

**Comment by felixhekhorn** [comment]
Closed in favor of #23

**Pull request closed without merging**
