### PR TITLE
Update docs

### LINKED ISSUE #4: Update README
The README isn't up-to-date and in particular it doesn't answer the important question: how do I run a process?

### PR DESCRIPTION
**Pull request by felixhekhorn**
Closes #4 

@comane and @t7phy can you please help? @andreab1997 maybe as well? just improve with your recent experience ...

e.g. we could consider adding the ssl discussion/snippet from #50 somewhere

### CODE REVIEW

**Comment by comane** [comment]
Hi @felixhekhorn , I have added a couple of lines regarding `openssl` as per #50

**Comment by AleCandido** [comment]
> Hi @felixhekhorn , I have added a couple of lines regarding `openssl` as per #50

Thanks @comane!

At the moment, the best thing to do is definitely document, since we're trying to converge on a stable version. However, a proper solution to it will be #7 (most likely, since the only one using OpenSSL should be Git)

**Comment by felixhekhorn** [comment]
> since the only one using OpenSSL should be Git

Actually it is cargo requiring ssl - so the solution is to use the [pre-built binaries](https://nnpdf.github.io/pineappl/docs/installation.html#using-pre-built-binaries)

**Comment by felixhekhorn** [comment]
let's merge something

@comane if you have time please improve whatever you can

@cschwan please have a look (even a quick one) and then we simply merge

**Comment by t7phy** [comment]
> Closes #4
> 
> @comane and @t7phy can you please help? @andreab1997 maybe as well? just improve with your recent experience ...
> 
> e.g. we could consider adding the ssl discussion/snippet from #50 somewhere

@felixhekhorn sorry I must have somehow missed this notification and just saw this. I have actually never used pinefarm

**Comment by felixhekhorn** [comment]
> @felixhekhorn sorry I must have somehow missed this notification and just saw this. I have actually never used pinefarm

@t7phy but you are running Matrix, right? so please consider seriously contributing to https://github.com/NNPDF/pinecards/pull/161 (which should really be a pinefarm PR)

**Comment by t7phy** [comment]
> 
> @t7phy but you are running Matrix, right? so please consider seriously contributing to [NNPDF/pinecards#161](https://github.com/NNPDF/pinecards/pull/161) (which should really be a pinefarm PR)

that is true, however while using matrix, personally, I have to always do lots of tweaking based on the requirements of specific run, and this is very situation based and not straightforward or trivial and I am unsure of how much of this can be automated. perhaps we can discuss this some day on how to go about this (based on all the bits and pieces that need to be thought about for every run individually)

**Comment by comane** [comment]
> @comane if you have time please improve whatever you can (also in a later PR)

Hi @felixhekhorn, I don't think I can actually contribute much to this PR.
I did not end up using pinefarm (madgralh) in the end. The only things I had noticed I already wrote down.
Also for Matrix as @t7phy  I used the Matrix code rather than pinefarm

**Pull request merged**
