### PR TITLE
Create theory_405.yaml

### PR DESCRIPTION
**Pull request by felixhekhorn**
port of https://github.com/NNPDF/runcards/pull/166

looks good to me by the way

### CODE REVIEW

**Comment by AleCandido** [comment]
Yes, it should be fine. At some point, I want to write a small function that downloads the theory db (either the SQL from the repo or the HTML table) and cache it locally, such that we can load from there.

Maybe we will still need some extra parameters, but these can be treated separately.

**Comment by andreab1997** [comment]
The theory card should be good. However when using it to compute the NLO DIS grids, it happens than the computed grids contain also the NNLO terms. Moreover, checking with `pineappl diff`, they are exactly the same as the theory 400 grids. Does this make sense to you? (cc @scarlehoff)

**Comment by AleCandido** [comment]
> it happens than the computed grids contain also the NNLO terms

This is fine, because it is FONLL-B

**Comment by andreab1997** [comment]
> The theory card should be good. However when using it to compute the NLO DIS grids, it happens than the computed grids contain also the NNLO terms. Moreover, checking with `pineappl diff`, they are exactly the same as the theory 400 grids. Does this make sense to you? (cc @scarlehoff)

Ok sorry, it seems that this was an error. So, everything should be fine as far as I understood.

**Review by andreab1997 — APPROVED** [review]

**Review by AleCandido — APPROVED** [review]
Maybe it's a bit outdated, but if still relevant it's fine.

If it's not relevant any longer, please close the PR.

**Comment by felixhekhorn** [comment]
It is indeed outdated and does not correspond to theory 405 any longer (no b displacement) ... I now think, we should not store theory cards here. This should be done on a more global level instead ... see also https://github.com/NNPDF/nnpdf/issues/1705 (cc @scarlehoff )

just to stress the point that we should do something sooner or later: on Friday @Radonirinaunimi was asking me for an official theory card and all I could do was to reply: "please ask @andreab1997, he knows"

**Pull request closed without merging**
